import { hashMap } from "./hashMap/hashMapFactory.js";
import { hashSet } from "./hashSet/hashSetFactory.js";
const test = new hashSet()

 test.set('apple', 'red')
 test.set('banana', 'yellow')
 test.set('carrot', 'orange')
 test.set('dog', 'brown')
 test.set('elephant', 'gray')
 test.set('frog', 'green')
 test.set('grape', 'purple')
 test.set('hat', 'black')
 test.set('ice cream')
 test.set('jacket')
 test.set('kite')
 test.set('lion')
 test.set('moon')
 test.set('man')
 test.set('golden')
 test.set('pink')
 test.set('blue')
 test.set('white')
 test.set('white')

console.log(test.has('black'))
console.log(test.length())
console.log(test.keys())
console.log(test.remove("blue"))
console.log(test.remove("blue"))
console.log(test.remove("lion"))
console.log(test.remove("kite"))
console.log(test.remove("jacket"))
console.log(test.remove("man"))
console.log(test.remove("moon"))